//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidus.SuicaTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TerminalType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidus.SuicaTools.Resources.TerminalType", typeof(TerminalType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Fare Gate.
        /// </summary>
        internal static string ConnectingFareGate {
            get {
                return ResourceManager.GetString("ConnectingFareGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Machine.
        /// </summary>
        internal static string DepositMachine {
            get {
                return ResourceManager.GetString("DepositMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Deposit Machine.
        /// </summary>
        internal static string EasyDepositMachine {
            get {
                return ResourceManager.GetString("EasyDepositMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fare Adjustment Machine.
        /// </summary>
        internal static string FareAdjustmentMachine {
            get {
                return ResourceManager.GetString("FareAdjustmentMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fare Gate.
        /// </summary>
        internal static string FareGate {
            get {
                return ResourceManager.GetString("FareGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fare Gate Terminal.
        /// </summary>
        internal static string FareGateTerminal {
            get {
                return ResourceManager.GetString("FareGateTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Phone.
        /// </summary>
        internal static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-board Terminal.
        /// </summary>
        internal static string OnboardTerminal {
            get {
                return ResourceManager.GetString("OnboardTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point of Sale.
        /// </summary>
        internal static string PointOfSale {
            get {
                return ResourceManager.GetString("PointOfSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable Terminal.
        /// </summary>
        internal static string PortableTerminal {
            get {
                return ResourceManager.GetString("PortableTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Fare Gate.
        /// </summary>
        internal static string SimpleFareGate {
            get {
                return ResourceManager.GetString("SimpleFareGate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Vending Machine.
        /// </summary>
        internal static string TicketVendingMachine {
            get {
                return ResourceManager.GetString("TicketVendingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Window Terminal.
        /// </summary>
        internal static string TicketWindowTerminal {
            get {
                return ResourceManager.GetString("TicketWindowTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Fare Adjustment Machine.
        /// </summary>
        internal static string TransferFareAdjustmentMachine {
            get {
                return ResourceManager.GetString("TransferFareAdjustmentMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Vending Machine.
        /// </summary>
        internal static string TVMLike {
            get {
                return ResourceManager.GetString("TVMLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vending &lt;achine.
        /// </summary>
        internal static string VendingMachine {
            get {
                return ResourceManager.GetString("VendingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW ALTTE.
        /// </summary>
        internal static string ViewAltte {
            get {
                return ResourceManager.GetString("ViewAltte", resourceCulture);
            }
        }
    }
}
