//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solidus.SuicaTools.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TransactionType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solidus.SuicaTools.Resources.TransactionType", typeof(TransactionType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benefit Charge.
        /// </summary>
        internal static string BenefitCharge {
            get {
                return ResourceManager.GetString("BenefitCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Charge.
        /// </summary>
        internal static string Bus_Deposit {
            get {
                return ResourceManager.GetString("Bus_Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        internal static string Bus_IruCa {
            get {
                return ResourceManager.GetString("Bus_IruCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        internal static string Bus_PiTaPa {
            get {
                return ResourceManager.GetString("Bus_PiTaPa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Purchase (non-rail).
        /// </summary>
        internal static string Bus_SpecialTicketPurchase {
            get {
                return ResourceManager.GetString("Bus_SpecialTicketPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string Charge {
            get {
                return ResourceManager.GetString("Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Deposit.
        /// </summary>
        internal static string Deposit_Registration {
            get {
                return ResourceManager.GetString("Deposit_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-charge on Entry.
        /// </summary>
        internal static string Entrance_AutoCharge {
            get {
                return ResourceManager.GetString("Entrance_AutoCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission &amp; Goods.
        /// </summary>
        internal static string EntranceGoods_AdmissionAndGoods {
            get {
                return ResourceManager.GetString("EntranceGoods_AdmissionAndGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-charge on Exit.
        /// </summary>
        internal static string Exit_AutoCharge {
            get {
                return ResourceManager.GetString("Exit_AutoCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fare Adjustment.
        /// </summary>
        internal static string FareAdjustment {
            get {
                return ResourceManager.GetString("FareAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fare Payment.
        /// </summary>
        internal static string FarePayment {
            get {
                return ResourceManager.GetString("FarePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card.
        /// </summary>
        internal static string NewIssue {
            get {
                return ResourceManager.GetString("NewIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reissue Card.
        /// </summary>
        internal static string Reissue {
            get {
                return ResourceManager.GetString("Reissue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale of Goods.
        /// </summary>
        internal static string SaleOfGoods {
            get {
                return ResourceManager.GetString("SaleOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settlement.
        /// </summary>
        internal static string Settlement {
            get {
                return ResourceManager.GetString("Settlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shinkansen Payment.
        /// </summary>
        internal static string ShinkansenPayment {
            get {
                return ResourceManager.GetString("ShinkansenPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Admission.
        /// </summary>
        internal static string ThirdParty_Admission {
            get {
                return ResourceManager.GetString("ThirdParty_Admission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-party Purchase.
        /// </summary>
        internal static string ThirdParty_Purchase {
            get {
                return ResourceManager.GetString("ThirdParty_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Office Deduction.
        /// </summary>
        internal static string TicketOfficeDeduction {
            get {
                return ResourceManager.GetString("TicketOfficeDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staffed Ticket Window Exit.
        /// </summary>
        internal static string TicketOfficeExit {
            get {
                return ResourceManager.GetString("TicketOfficeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Purchase.
        /// </summary>
        internal static string TicketPurchase {
            get {
                return ResourceManager.GetString("TicketPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void Sale.
        /// </summary>
        internal static string VoidSaleOfGoods {
            get {
                return ResourceManager.GetString("VoidSaleOfGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物現.
        /// </summary>
        internal static string 物現 {
            get {
                return ResourceManager.GetString("物現", resourceCulture);
            }
        }
    }
}
